DROP DATABASE IF EXISTS TA26_EX1;
CREATE DATABASE TA26_EX1;
USE TA26_EX1;

CREATE TABLE piezas(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre varchar(100)
);

CREATE TABLE proveedores(
id char(4) PRIMARY KEY,
nombre varchar(100)
);

CREATE TABLE suministra(
id INT AUTO_INCREMENT PRIMARY KEY,
pieza INT,
proveedor char(4),
FOREIGN KEY (pieza) REFERENCES piezas(id) ON DELETE CASCADE ON UPDATE SET NULL,
FOREIGN KEY (proveedor) REFERENCES proveedores(id) ON DELETE CASCADE ON UPDATE SET NULL
);